---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_items: "{{ ansible_os_family | lower }}.yml"
  tags:
    - always

- import_tasks: preflight.yml

- import_tasks: install.yml

- import_tasks: configure.yml

- name: ensure starts on system boot
  systemd:
    name: docker
    enabled: true
